import { SDXClassValidatorMap } from './class-validator-map';

export interface SDXTypeDeactivator {
  deactivate: 'string' | 'number' | 'object' | 'array' | null;
}

export const SDX_TYPE_DEACTIVATORS: Record<
  keyof typeof SDXClassValidatorMap,
  SDXTypeDeactivator
> = {
  // --- TYPE DEACTIVATORS (Validators que desativam o próprio tipo) ---
  IsString: { deactivate: 'string' },
  IsNumber: { deactivate: 'number' },
  IsArray: { deactivate: 'array' },
  IsObject: { deactivate: 'object' },

  // --- STRING DEACTIVATORS (Validadores que implicam ser String) ---
  Contains: { deactivate: 'string' },
  NotContains: { deactivate: 'string' },
  IsAlpha: { deactivate: 'string' },
  IsAlphanumeric: { deactivate: 'string' },
  IsAscii: { deactivate: 'string' },
  IsBase64: { deactivate: 'string' },
  IsByteLength: { deactivate: 'string' },
  IsCreditCard: { deactivate: 'string' },
  IsCurrency: { deactivate: 'string' },
  IsEmail: { deactivate: 'string' },
  IsFQDN: { deactivate: 'string' },
  IsFullWidth: { deactivate: 'string' },
  IsHalfWidth: { deactivate: 'string' },
  IsVariableWidth: { deactivate: 'string' },
  IsHexColor: { deactivate: 'string' },
  IsHexadecimal: { deactivate: 'string' },
  IsMACAddress: { deactivate: 'string' },
  IsIP: { deactivate: 'string' },
  IsISBN: { deactivate: 'string' },
  IsISIN: { deactivate: 'string' },
  IsISO8601: { deactivate: 'string' },
  IsJSON: { deactivate: 'string' },
  IsJWT: { deactivate: 'string' },
  IsLowercase: { deactivate: 'string' },
  IsUppercase: { deactivate: 'string' },
  IsMobilePhone: { deactivate: 'string' },
  IsISO31661Alpha2: { deactivate: 'string' },
  IsISO31661Alpha3: { deactivate: 'string' },
  IsMongoId: { deactivate: 'string' },
  IsMultibyte: { deactivate: 'string' },
  IsSurrogatePair: { deactivate: 'string' },
  IsUrl: { deactivate: 'string' },
  IsUUID: { deactivate: 'string' },
  IsFirebasePushId: { deactivate: 'string' },
  IsPhoneNumber: { deactivate: 'string' },
  IsMilitaryTime: { deactivate: 'string' },
  IsHash: { deactivate: 'string' },
  IsISSN: { deactivate: 'string' },
  IsDateString: { deactivate: 'string' },
  IsBooleanString: { deactivate: 'string' },
  IsNumberString: { deactivate: 'string' },
  IsBase32: { deactivate: 'string' },
  IsBIC: { deactivate: 'string' },
  IsBtcAddress: { deactivate: 'string' },
  IsDataURI: { deactivate: 'string' },
  IsEAN: { deactivate: 'string' },
  IsEthereumAddress: { deactivate: 'string' },
  IsHSL: { deactivate: 'string' },
  IsIBAN: { deactivate: 'string' },
  IsIdentityCard: { deactivate: 'string' },
  IsISRC: { deactivate: 'string' },
  IsLocale: { deactivate: 'string' },
  IsMagnetURI: { deactivate: 'string' },
  IsMimeType: { deactivate: 'string' },
  IsOctal: { deactivate: 'string' },
  IsPassportNumber: { deactivate: 'string' },
  IsPostalCode: { deactivate: 'string' },
  IsRFC3339: { deactivate: 'string' },
  IsRgbColor: { deactivate: 'string' },
  IsSemVer: { deactivate: 'string' },
  IsStrongPassword: { deactivate: 'string' },
  IsTimeZone: { deactivate: 'string' },
  IsBase58: { deactivate: 'string' },
  IsTaxId: { deactivate: 'string' },
  IsISO4217CurrencyCode: { deactivate: 'string' },
  Length: { deactivate: 'string' },
  MaxLength: { deactivate: 'string' },
  MinLength: { deactivate: 'string' },
  Matches: { deactivate: 'string' },

  // --- NUMBER DEACTIVATORS (Validadores que implicam ser Number) ---
  IsDivisibleBy: { deactivate: 'number' },
  IsInt: { deactivate: 'number' },
  IsPositive: { deactivate: 'number' },
  IsNegative: { deactivate: 'number' },
  IsDecimal: { deactivate: 'number' },
  Max: { deactivate: 'number' },
  Min: { deactivate: 'number' },
  IsPort: { deactivate: 'number' },

  // --- ARRAY DEACTIVATORS (Validadores que implicam ser Array) ---
  ArrayContains: { deactivate: 'array' },
  ArrayNotContains: { deactivate: 'array' },
  ArrayNotEmpty: { deactivate: 'array' },
  ArrayMinSize: { deactivate: 'array' },
  ArrayMaxSize: { deactivate: 'array' },
  ArrayUnique: { deactivate: 'array' },

  // --- OBJECT DEACTIVATORS ---
  IsNotEmptyObject: { deactivate: 'object' },
  IsInstance: { deactivate: 'object' },

  // --- NULL/MISC (Não garantem um tipo primitivo específico ou dependem do input) ---
  Allow: { deactivate: null },
  Equals: { deactivate: null },
  NotEquals: { deactivate: null },
  IsDefined: { deactivate: null },
  IsOptional: { deactivate: null },
  IsIn: { deactivate: null },
  IsNotIn: { deactivate: null },
  IsEmpty: { deactivate: null },
  IsNotEmpty: { deactivate: null },
  IsBoolean: { deactivate: null },
  IsDate: { deactivate: null },
  IsEnum: { deactivate: null },
  IsLatLong: { deactivate: null },
  IsLatitude: { deactivate: null },
  IsLongitude: { deactivate: null },
  MinDate: { deactivate: null },
  MaxDate: { deactivate: null },
  Validate: { deactivate: null },
  ValidateBy: { deactivate: null },
  ValidateIf: { deactivate: null },
  ValidateNested: { deactivate: null },
  ValidatePromise: { deactivate: null },
};
